---
- hosts: app
  become: true
  tasks:
    # - name: Install required system packages
    #   apt: name={{ item }} state=latest update_cache=yes
    #   loop: [ 'docker', 'docker-compose', 'nodejs']

    - git:
        repo: https://github.com/ColinRoye/account_service
        dest: /app
        force: yes
    - name: Run mix commands
      shell: cd /app
               && echo y | sudo docker system prune
               && sudo sysctl -w vm.max_map_count=524288
               && npm install
               && sudo docker-compose up > deploy_log
      ignore_errors: yes

      become: True
